[package]
name = "steam_dev_launcher"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
simplelog = "0.12"
log = "0.4"
clap = { version = "4.0", features = ["derive"] }
